/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mecatronica_2019;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhow
 */
public class Main extends javax.swing.JFrame {

    //==== MYSQL
    public static String Senha = null;//Senha MySQL
    public static String Usuario = null;//Usuario MySQL
    public static String Banco = null;//Base de Dados MySQL
    public static String Host = null;//Ip MySQL
    public static String Port = null;//Ip MySQL
    public static MySQL mysql = null;//Return MYSQL
    //
    public static Main instance;//DEFINIÇAO COMPARTILHAVEL DA CLASSE MAIN
    public static TableColumModel model;
    public static Cache cache;

    /**
     * Creates new form FrameS
     */
    public Main() {
        instance = this;//INICIALIZA A CONSTANTE INSTANCE
        Usuario = "REMOVIDO";//DEFINE OS DADOS DO MYSQL
        Senha = "REMOVIDO";// **
        Banco = "REMOVIDO";// **
        Host = "REMOVIDO";// **
        Port = "3306";// **
        mysql = new MySQL();//FAZ O CAST DA CLASSE MYSQL
        try {
            mysql.start();//EXECUTA O METODO START SETADO NA CLASSE MYSQL
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();//gerado pelo IDE
        ImageIcon ico = new ImageIcon(getClass().getResource("ico.jpg"));//BUSCA O ICONE DENTRO DO PACOTE
        setIconImage(ico.getImage());//SETA ICON IMAGE COM O ICONE DECLARADO
        //
        model = new TableColumModel();//CAST DA CLASSE TABLECOLUMMODEL
        tabela.setModel(model);//DEFINE O MODEL DA TABELA COMO model
        cache = new Cache();//INICIALIZA O CACHE
        cache.init();// BUSCA E CADASTRA AS QUERYS NA ARRAY OBJECT
    }

    // <editor-fold defaultstate="collapsed" desc="CODIGO GERADO PELA IDE">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tabelaPanel = new javax.swing.JTabbedPane();
        nova_fichaPanel = new javax.swing.JPanel();
        tagLabel = new javax.swing.JLabel();
        tagText = new javax.swing.JTextField();
        dataLabel = new javax.swing.JLabel();
        dataText = new javax.swing.JTextField();
        tipoLabel = new javax.swing.JLabel();
        tipoText = new javax.swing.JTextField();
        respLabel = new javax.swing.JLabel();
        respText = new javax.swing.JTextField();
        descLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descText = new javax.swing.JTextArea();
        salvarButton = new javax.swing.JButton();
        descartarButton = new javax.swing.JButton();
        grupoRollbox = new javax.swing.JComboBox<>();
        grupoLabel = new javax.swing.JLabel();
        historicoPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        listarButton = new javax.swing.JButton();
        listarText = new javax.swing.JTextField();
        gerarButton = new javax.swing.JButton();
        data2Label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestao e Controle de Manutenção Industrial");
        setResizable(false);

        tabelaPanel.setMaximumSize(new java.awt.Dimension(440, 500));
        tabelaPanel.setPreferredSize(new java.awt.Dimension(345, 400));

        nova_fichaPanel.setBackground(new java.awt.Color(204, 204, 204));
        nova_fichaPanel.setForeground(new java.awt.Color(153, 255, 255));
        nova_fichaPanel.setMaximumSize(new java.awt.Dimension(340, 400));
        nova_fichaPanel.setPreferredSize(new java.awt.Dimension(340, 400));

        tagLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tagLabel.setForeground(new java.awt.Color(0, 0, 51));
        tagLabel.setText("Etiqueta:");

        tagText.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tagText.setToolTipText("");
        tagText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tagText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagTextActionPerformed(evt);
            }
        });

        dataLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        dataLabel.setForeground(new java.awt.Color(0, 0, 51));
        dataLabel.setText("Data da Manutenção:");

        dataText.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        dataText.setToolTipText("");
        dataText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dataText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTextActionPerformed(evt);
            }
        });

        tipoLabel.setBackground(new java.awt.Color(0, 0, 51));
        tipoLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tipoLabel.setForeground(new java.awt.Color(0, 0, 51));
        tipoLabel.setText("Tipo de Equipamento:");

        tipoText.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tipoText.setToolTipText("");
        tipoText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tipoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoTextActionPerformed(evt);
            }
        });

        respLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        respLabel.setForeground(new java.awt.Color(0, 0, 51));
        respLabel.setText("Responsavel:");

        respText.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        respText.setToolTipText("");
        respText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        respText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respTextActionPerformed(evt);
            }
        });

        descLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        descLabel.setForeground(new java.awt.Color(0, 0, 51));
        descLabel.setText("Descrição do Equipamento:");

        descText.setColumns(20);
        descText.setLineWrap(true);
        descText.setRows(5);
        descText.setAutoscrolls(false);
        descText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        descText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(descText);

        salvarButton.setBackground(new java.awt.Color(255, 255, 255));
        salvarButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        salvarButton.setForeground(new java.awt.Color(0, 0, 0));
        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        descartarButton.setBackground(new java.awt.Color(255, 255, 255));
        descartarButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        descartarButton.setForeground(new java.awt.Color(0, 0, 0));
        descartarButton.setText("Descartar");
        descartarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarButtonActionPerformed(evt);
            }
        });

        grupoRollbox.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        grupoRollbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bancada 1", "Bancada 2", "Bancada 3", "Bancada 4", "Bancada 5", "Bancada 6", "Bancada 7", "Bancada 8", "Bancada 9", "Bancada 10", "Bancada 11", "Bancada 12", "Bancada 13", "Bancada 14", "Bancada 15" }));
        grupoRollbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoRollboxActionPerformed(evt);
            }
        });

        grupoLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        grupoLabel.setForeground(new java.awt.Color(0, 0, 51));
        grupoLabel.setText("BANCADA:");

        javax.swing.GroupLayout nova_fichaPanelLayout = new javax.swing.GroupLayout(nova_fichaPanel);
        nova_fichaPanel.setLayout(nova_fichaPanelLayout);
        nova_fichaPanelLayout.setHorizontalGroup(
            nova_fichaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nova_fichaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nova_fichaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nova_fichaPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(nova_fichaPanelLayout.createSequentialGroup()
                        .addGroup(nova_fichaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tagText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tagLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(nova_fichaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataLabel))
                        .addGap(34, 34, 34))
                    .addGroup(nova_fichaPanelLayout.createSequentialGroup()
                        .addComponent(tipoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(respLabel)
                        .addGap(101, 101, 101))
                    .addGroup(nova_fichaPanelLayout.createSequentialGroup()
                        .addComponent(tipoText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(respText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(nova_fichaPanelLayout.createSequentialGroup()
                        .addComponent(descLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(nova_fichaPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(salvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descartarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(nova_fichaPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(grupoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grupoRollbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        nova_fichaPanelLayout.setVerticalGroup(
            nova_fichaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nova_fichaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nova_fichaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagLabel)
                    .addComponent(dataLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nova_fichaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nova_fichaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoLabel)
                    .addComponent(respLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nova_fichaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(nova_fichaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grupoLabel)
                    .addComponent(grupoRollbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(nova_fichaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarButton)
                    .addComponent(descartarButton))
                .addContainerGap())
        );

        tabelaPanel.addTab("Nova Ficha", null, nova_fichaPanel, "");

        historicoPanel.setBackground(new java.awt.Color(204, 204, 204));
        historicoPanel.setForeground(new java.awt.Color(204, 204, 204));
        historicoPanel.setMaximumSize(new java.awt.Dimension(340, 400));
        historicoPanel.setPreferredSize(new java.awt.Dimension(340, 400));

        tabela.setBackground(new java.awt.Color(255, 255, 255));
        tabela.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tabela.setForeground(new java.awt.Color(0, 0, 0));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATA", "ETIQUETA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela.setToolTipText("");
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabela);

        listarButton.setBackground(new java.awt.Color(255, 255, 255));
        listarButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        listarButton.setForeground(new java.awt.Color(0, 0, 0));
        listarButton.setText("Listar");
        listarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarButtonActionPerformed(evt);
            }
        });

        listarText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarTextActionPerformed(evt);
            }
        });

        gerarButton.setBackground(new java.awt.Color(0, 0, 255));
        gerarButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gerarButton.setForeground(new java.awt.Color(0, 0, 0));
        gerarButton.setText("Visualizar");
        gerarButton.setToolTipText("");
        gerarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarButtonActionPerformed(evt);
            }
        });

        data2Label.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        data2Label.setForeground(new java.awt.Color(0, 0, 51));
        data2Label.setText("DATA:");

        javax.swing.GroupLayout historicoPanelLayout = new javax.swing.GroupLayout(historicoPanel);
        historicoPanel.setLayout(historicoPanelLayout);
        historicoPanelLayout.setHorizontalGroup(
            historicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historicoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(data2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listarText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(historicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listarButton)
                    .addComponent(gerarButton))
                .addGap(44, 44, 44))
        );
        historicoPanelLayout.setVerticalGroup(
            historicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historicoPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(historicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listarButton)
                    .addComponent(data2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gerarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabelaPanel.addTab("Histórico", historicoPanel);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\t\nMelhorada estrutura do Cache.(16/08/2019)");
        jScrollPane2.setViewportView(jTextArea1);

        jTextField2.setEditable(false);
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setText("Projeto Desenvolvido com fins academicos.");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("MECATRONICA 2019.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 82, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaPanel.addTab("ChangeLog", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tabelaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(346, 447));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tagTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tagTextActionPerformed

    private void dataTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataTextActionPerformed

    private void tipoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoTextActionPerformed

    private void respTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respTextActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        // TODO add your handling code here:
        String tag = "";
        if (tagText != null) {
            tag = tagText.getText();//DEFINE A STRING TAG FAZENDO CAST DA tagText
        }
        String date = "";
        if (dataText != null) {
            date = dataText.getText();//DEFINE A STRING date FAZENDO CAST DA dataText
        }
        String type = "";
        if (tipoText != null) {
            type = tipoText.getText();//DEFINE A STRING type FAZENDO CAST DA tipoText
        }
        String autor_uno = "";
        if (respText != null) {
            autor_uno = respText.getText();//DEFINE A STRING autor_uno FAZENDO CAST DA respText
        }
        String autor_group = "";
        if (grupoRollbox != null) {
            autor_group = grupoRollbox.getSelectedItem().toString();//DEFINE A STRING autor_group FAZENDO CAST DA grupoRollbox
        }
        String desc_t = "";
        if (descText != null) {
            desc_t = descText.getText();//DEFINE A STRING desc_t FAZENDO CAST DA descText
        }        //
        if (!tag.equals("")
                && !date.equals("")
                && !type.equals("")
                && !autor_uno.equals("")
                && !autor_group.equals("")
                && !desc_t.equals("")) {
            Ficha f = new Ficha().Ficha(tag, date, type, autor_uno, autor_group, desc_t);//CONSTROI A FICHA E FAZ CAST DA CLASSE
            f.insert();//INSERTA A FICHA NA TABELA
            cache.getFichas().add(f);
            //
            JOptionPane.showMessageDialog(rootPane, "Ficha salva com sucesso!");
            reset();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ops, falta preencher alguns campos...");
        }
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void descartarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarButtonActionPerformed
        // TODO add your handling code here:
        reset();
        JOptionPane.showMessageDialog(rootPane, "Ficha apagada com sucesso!");
    }//GEN-LAST:event_descartarButtonActionPerformed

    private void grupoRollboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoRollboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grupoRollboxActionPerformed

    private void listarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarButtonActionPerformed
        // TODO add your handling code here:
        if (model.dados.size() > 0) {
            model.dados.clear();
        }
        String data = "";
        if (listarText != null) {
            data = listarText.getText();
        }
        if (cache.has()) {
            for (Ficha f : cache.getFichas()) {
                if (f.getData().equals(data)) {
                    model.addRow(f);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não achamos nenhuma ficha com esta data...");
        }

    }//GEN-LAST:event_listarButtonActionPerformed

    private void listarTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarTextActionPerformed

    private void gerarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarButtonActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() >= 0) {
            Ficha f = model.dados.get(tabela.getSelectedRow());
            TableColumModel.ficha = f;
            FichaFrame ff = new FichaFrame();
            ff.setVisible(true);
            ff.update();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma ficha na tabela.");
        }
    }//GEN-LAST:event_gerarButtonActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel data2Label;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JTextField dataText;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextArea descText;
    private javax.swing.JButton descartarButton;
    private javax.swing.JButton gerarButton;
    private javax.swing.JLabel grupoLabel;
    private javax.swing.JComboBox<String> grupoRollbox;
    private javax.swing.JPanel historicoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton listarButton;
    private javax.swing.JTextField listarText;
    private javax.swing.JPanel nova_fichaPanel;
    private javax.swing.JLabel respLabel;
    private javax.swing.JTextField respText;
    private javax.swing.JButton salvarButton;
    private javax.swing.JTable tabela;
    private javax.swing.JTabbedPane tabelaPanel;
    private javax.swing.JLabel tagLabel;
    private javax.swing.JTextField tagText;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JTextField tipoText;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>

    private void reset() {
        dataText.setText("");
        descText.setText("");
        grupoRollbox.setSelectedIndex(0);
        respText.setText("");
        tagText.setText("");
        tipoText.setText("");
        dataText.setText("");
    }
}
